adjective = input("Enter an adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
exclamation = input("Enter an exclamation: ")
verb2 = input("Enter another verb: ")
verb3 = input("Enter another verb: ")

print("Your story is:")
print()
print(f"The other day, I was really in trouble. It all started when I saw a very") 
print(f"{adjective} {noun} {verb} down the hallway.", end=" ")
print(f'"{exclamation.capitalize()}!'" I yelled. But all")
print(f"I could think to do was to {verb2} over and over. Miraculously,")
print(f"that caused it to stop, but not before it tried to {verb3}")
print("right in front of my family")